export const skillIcons = {
    HTML: 'html.png',
    CSS: 'css.png',
    JavaScript: 'javascript.png',
    TypeScript: 'typescript.png',
    React: 'react.svg',
    "Node.js": 'nodejs.png',
    PHP: 'php.png',
    "Ruby (on Rails)": 'rails.png',
    Java: 'java.png',
    "Express.js": 'expressjs.png',
    "Axios.js": 'axiosjs.png',
    "Netlify Functions": 'netlify.png',
    "SQL (MySQL, MariaDB)": 'sql.png',
    "Dart (Flutter)": 'flutter.png',
    Bash: 'bash.png',
    Fish: 'fish.png',
    "GNU/Linux": 'linux.jpg',
  };
